### ISSUE TITLE
Singledb does not drop schema objects

### ISSUE THREAD

**Issue by Xiaoming-lw** [littleK0i/SnowDDL#140] opened 2024-10-31 23:26 UTC
**Describe the bug**
The `drop schema` SQL is not produced while running the snowddl-singledb.

**Expected behavior**
It seems to be a bug, but I am not sure is this a feature.

**Attach log**
```
# snowddl -c sample02_01 --apply-unsafe --apply-masking-policy --apply-row-access-policy apply
# snowddl-singledb -c sample02_01 --config-db=TEST_DB --target-db=ANOTHER_DB --apply-unsafe --apply-masking-policy --apply-row-access-policy apply
# rm -rf snowddl/_config/sample02_01/test_db/test_schema
# snowddl-singledb -c sample02_01 --config-db=TEST_DB --target-db=ANOTHER_DB --apply-unsafe --apply-masking-policy --apply-row-access-policy plan
2024-10-31 16:23:26.944 - INFO - Snowflake version = 8.41.1 (ENTERPRISE), SnowDDL version = 0.34.3
2024-10-31 16:23:26.944 - INFO - Account =
2024-10-31 16:23:26.944 - INFO - Session = 149589471468150, User = SNOWDDL_TEST
2024-10-31 16:23:26.944 - INFO - Role = SNOWDDL_XL__SNOWDDL_ADMIN_TEST, Warehouse = SNOWDDL_WH
2024-10-31 16:23:26.945 - INFO - Roles in session = ACCOUNTADMIN,SYSADMIN,SECURITYADMIN
2024-10-31 16:23:26.945 - INFO - ---
2024-10-31 16:23:34.922 - INFO - Executed 0 DDL queries, Suggested 0 DDL queries
```

**Comment by littleK0i** [comment] 2024-11-03 11:16
Should be fixed in 0.34.4

Commit: https://github.com/littleK0i/SnowDDL/commit/19e341f97c84aeca70140c8b723bcd15d49ac300

Thank you!

**Comment by Xiaoming-lw** [comment] 2024-11-06 17:44
If the `another_db` is not exist, there would be an error for database not created while run singledb directly. Is this an issue?

```
snowddl-singledb -c sample02_01 --config-db=TEST_DB --target-db=ANOTHER_DB --apply-unsafe --apply-masking-policy --apply-row-access-policy apply

......

2024-11-06 09:42:55.615 - WARNING - Resolved SCHEMA [SNOWDDL_XL__ANOTHER_DB.TEST_SCHEMA]: ERROR
(
    message   =>  SQL compilation error:
Database 'SNOWDDL_XL__ANOTHER_DB' does not exist or not authorized.
    errno     =>  2003
    sqlstate  =>  02000
    sfqid     =>  01b831c6-0103-a1ab-0000-880d0e73332a
    sql       =>  CREATE SCHEMA "SNOWDDL_XL__ANOTHER_DB"."TEST_SCHEMA"
WITH MANAGED ACCESS
)

```

**Comment by littleK0i** [comment] 2024-11-07 09:55
Should be alright, since SingleDB assumes DB already exists and was created by something or someone else. SingleDB starts with schemas.

**Comment by TedCha** [comment] 2024-11-07 16:30
Hello! I wanted to point out something that we ran in to. Not sure if this is a bug or is working as expected.

For context, we're using SnowDDL in single database mode as the DCM tool for multiple data sets. These data sets don't all exist in the same Git repository, but each data set contains separate schemas.

**Example:** 

Repository 1:
```text
config/
└── DATABASE/
    └── PRODUCT1_SCHEMA/
        └── table/
            └── PRODUCT1_TABLE_V1.yaml
```

Repository 2:
```text
config/
└── DATABASE/
    └── PRODUCT2_SCHEMA/
        └── table/
            └── PRODUCT2_TABLE_V1.yaml
```

Before this change was implemented, only objects in Snowflake within the schema would be dropped rather than other schemas.

Repository 1 Plan (before change):
```text
Context: PRODUCT1_TABLE_V1 was renamed to PRODUCT1_TABLE_V2.

Command snowddl-singledb -c ./config --config-db DATABASE plan

2024-11-07 11:05:16.594 - INFO - Resolved TABLE [DATABASE.PRODUCT1_SCHEMA.PRODUCT1_TABLE_V1]: DROP
2024-11-07 11:05:16.594 - INFO - Resolved TABLE [DATABASE.PRODUCT1_SCHEMA.PRODUCT1_TABLE_V2]: CREATE
```

With this change implemented, schemas that don't exist within the config for a repository will now be dropped when the `params.yaml` file for the database doesn't have `is_sandbox` enabled.

Repository 1 Plan (after change):
```text
Context: PRODUCT1_TABLE_V1 was renamed to PRODUCT1_TABLE_V2.

Command snowddl-singledb -c ./config --config-db DATABASE plan

2024-11-07 11:05:15.171 - INFO - Resolved SCHEMA [DATABASE.PRODUCT2_SCHEMA]: DROP
2024-11-07 11:05:16.594 - INFO - Resolved TABLE [DATABASE.PRODUCT1_SCHEMA.PRODUCT1_TABLE_V1]: DROP
2024-11-07 11:05:16.594 - INFO - Resolved TABLE [DATABASE.PRODUCT1_SCHEMA.PRODUCT1_TABLE_V2]: CREATE
```

I thought the fix would be to add a `params.yaml` file with `is_sandbox: true` to the database, but that actually enables the schema to be in sandbox mode too.

Repository 1 (with `params.yaml` file):
```text
config/
└── DATABASE/
    ├── PRODUCT1_SCHEMA/
    │   └── table/
    │       └── PRODUCT1_TABLE_V1.yaml
    └── params.yaml
```

Repository 1 `params.yaml` file:
```yaml
is_sandbox: true
```

Repository 1 Plan (after change w/`params.yaml` file):
```text
Context: PRODUCT1_TABLE_V1 was renamed to PRODUCT1_TABLE_V2.

Command snowddl-singledb -c ./config --config-db DATABASE plan

2024-11-07 11:05:15.171 - INFO - Resolved SCHEMA [DATABASE.PRODUCT2_SCHEMA]: DROP
2024-11-07 11:05:16.594 - INFO - Resolved TABLE [DATABASE.PRODUCT1_SCHEMA.PRODUCT1_TABLE_V2]: CREATE
```

I would expect that if `is_sandbox` is enabled at the database level it wouldn't be enabled at the schema level. We could solve this on our side by consolidating all of our data sets into one repository but that wouldn't be my preferred solution.

Apologies if this issue isn't clear, please let me know if there's any confusion and I'll create a reproducible example. Thanks again for all of your work!

**Comment by littleK0i** [comment] 2024-11-07 18:21
@TedCha , in theory, we may now allow `is_sandbox: false` on schema level to override `is_sandbox: true` on database level, if specified explicitly.

The original implementation comes from very organized environment when all schemas are well-known in advanced and defined in the same config. But now we have permission models which potentially allow external scripts to create new schemas, so potentially this adjustment might be useful.

Naturally, I would also suggest to consolidate all schemas into one config, especially if objects in one schema may reference objects in another schema. And if these schemas have no references and should be managed separately, maybe they belong to different databases.

**Comment by TedCha** [comment] 2024-11-07 19:02
@littleK0i 

Thanks for the quick response!

> Naturally, I would also suggest to consolidate all schemas into one config, especially if objects in one schema may reference objects in another schema. And if these schemas have no references and should be managed separately, maybe they belong to different databases.

For the most part our schemas are separate from one another (if they're not, they under the same config in a repository). The reason why we use schemas to separate entities is because we only have permissions to act within one specified database. We might be using SnowDDL inappropriately, if that is the case, my apologies for the bother!

Otherwise, allowing `is_sandbox: false` at the schema level to override `is_sandbox: true` at the database level would work perfectly for us. From a broader perspective, I think it would be useful for other users as well because objects at the database level can be "external" to SnowDDL while objects at the schema level can be "internal" to SnowDDL if they explicitly define it that way. I'm not sure how widely used the feature would be but it offers a good amount of flexibility while still enabling default behavior.

I'd be happy to put in a PR if you agree. I think it would just be switching the logic [here](https://github.com/littleK0i/SnowDDL/blob/19e341f97c84aeca70140c8b723bcd15d49ac300/snowddl/parser/schema.py#L96) to check the schema params before checking the database params.

**Comment by littleK0i** [comment] 2024-11-07 19:28
@TedCha , that's correct place. Please go ahead with PR, thank you!

**Comment by littleK0i** [comment] 2024-11-08 11:39
@TedCha , should work in `0.35.0`.

**Comment by TedCha** [comment] 2024-11-08 13:39
@littleK0i Just tested, works perfectly. Thank you very much!

**Closed** 2024-11-11 12:33 UTC
